# See: https://taskfile.dev/api/

version: "3"

tasks:
  up:
    aliases:
      - up
    desc: "up migrations"
    cmds: 
      - migrate -source file://./migrations/ -database postgres://postgres:mypass@localhost:5431/urls?sslmode=disable up
  rollback:
    aliases:
      - down
    desc: "down migrations"
    cmds: 
      - migrate -source file://./migrations/ -database postgres://postgres:mypass@localhost:5432/urls?sslmode=disable down
  drop:
    aliases:
      - migrations_test
    desc: "run test migrations"
    cmds: 
     - migrate -source file://./migrations/ -database postgres://postgres:mypass@localhost:5432/urls?sslmode=disable drop
  generate:
    aliases:
      - migrate
    desc: "run migrations"
    cmds: 
      - go run ./cmd/migrator/ --url=postgres:mypass@localhost:5432 --dbname=urls --migrations-path=./migrations
  generate_test:
    aliases:
      - migrations_test
    desc: "run test migrations"
    cmds: 
      - go run ./cmd/migrator/ --url=postgres:mypass@localhost:5432 --dbname=urls --migrations-path=./tests/migrations --migrations-table=migrations_test

      # See: https://taskfile.dev/api/