# See: https://taskfile.dev/api/

version: "3"

tasks:
  up:
    aliases:
      - up
    desc: "up migrations"
    cmds: 
      - migrate -source file://./migrations/ -database postgres://myuser:mypass@localhost:5431/url?sslmode=disable up
  rollback:
    aliases:
      - down
    desc: "down migrations"
    cmds: 
      - migrate -source file://./migrations/ -database postgres://myuser:mypass@localhost:5432/url?sslmode=disable down
  drop:
    aliases:
      - "drop migrations"
    desc: "drop migrations"
    cmds: 
     - migrate -source file://./migrations/ -database postgres://myuser:mypass@localhost:5431/url?sslmode=disable drop
  db-start:
    aliases:
      - db-start
    desc: "run docker postgres"
    cmds:
      - docker run --name url-pos -e POSTGRES_DB=url -e POSTGRES_USER=myuser -e POSTGRES_PASSWORD=mypass -p 5431:5432 -d postgres


      # See: https://taskfile.dev/api/