env: "local" # local, prod
storage:
  host: "0.0.0.0"
  port: 5432
  dbname: "urls"
  user: "myuser"
  password: "mypass"
http_server:
  address: "localhost:8080"
  timeout: 4s # Время на чтение и отправку запроса
  idle_timeout: 60s # Время жизни соединения с клиентом
  user: "myuser"
  password: "mypass"
clients:
  sso:
    address: "localhost:44044"
    timeout: 15s
    retriesCount: 5
app_secret: "test-secret"
