env: "prod"
storage_path: "./storage/storage.db"
http_server:
  address: "172.17.2.169:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "Teddy1"
clients:
  address: "217.71.129.139:4532"
  timeout: 15s
  retriesCount: 5