env: "prod"
storage:
  host: "urldb"
  port: 5432
  migrations_path: "./migrations"
http_server:
  address: "url-shortener:8080"
  timeout: 4s # Время на чтение и отправку запроса
  idle_timeout: 60s # Время жизни соединения с клиентом
  user: "daddy"
clients:
  sso:
    address: "sso:44044"
    timeout: 15s
    retriesCount: 5